name: Pytest
on:
  pull_request:
    types: [opened]
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          restore-cache: true
          save-cache: true

      - name: Install dependencies
        run: |
          uv sync --locked --all-groups --all-extras --dev

      - name: Generate tl
        run: uv run python tools/tl_gen.py

      - name: Run tests
        run: |
          uv run pytest \
            --cov-append \
            --cov-report=xml \
            --cov=piltover/app \
            --cov=piltover/config \
            --cov=piltover/db \
            --cov=piltover/gateway \
            --cov=piltover/message_brokers \
            --cov=piltover/pubsub \
            --cov=piltover/session \
            --cov=piltover/storage \
            --cov=piltover/tl/layer_converters \
            --cov=piltover/tl/placeholders \
            --cov=piltover/tl/primitives \
            --cov=piltover/tl/to_format \
            --cov=piltover/tl/core_types.py \
            --cov=piltover/tl/serialization_context.py \
            --cov=piltover/tl/serialization_utils.py \
            --cov=piltover/tl/tl_object.py \
            --cov=piltover/tl/utils.py \
            --cov=piltover/utils \
            --cov=piltover/*.py \
            tests
        env:
          LOGURU_LEVEL: WARNING

      - name: Print coverage report
        run: |
          uv run coverage report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}